In [ ]:
import numpy as np
from sympy import *
debug = False

In [52]:
def Gauss_pivot(A, B):
    '''
    Elimination de Gauss avec Pivot.
    % Entree: A est matrice non singuliere (n,n)
    %       B est un vecteur de n elements
    % X est la solution du systeme  AX = B
    % post-condition: A and b have been modified.
    '''
    #A = M
    #B = b
    n =  len(A)
    print('n = ',n)
    if B.size != n:
        raise ValueError("Argument invalide : Incompatibilite de taille entre A  et B ", B.size, n)
    # k represente la ligne du pivot courant . 

    for k in  range(n-1):
        #On choisit le pivot maximal k

        maxindex = abs(A[k:,k]).argmax() + k
        if debug :print('maxindex = ',maxindex, k)
        if abs(A[maxindex, k]) < 0.000000001:
            raise ValueError("La matrice A est singuliere.")
        # On permute les lignes
        if maxindex != k:
            A[[k,maxindex]] = A[[maxindex, k]]
            B[[k,maxindex]] = B[[maxindex, k]]
            if debug :print('A permut=',A)
        for row in  range(k+1, n):
            multiplier = A[row][k]/A[k][k]
            #  Le reste de la colonne est nul
            A[row][k] = multiplier
            for col in range(k + 1, n):
                A[row][col] = A[row][col] - multiplier*A[k][col]
            # La solution de l'equation est maintenant dans B
            B[row] = B[row] - multiplier*B[k]
        if debug :
            print('A = ',A)
            print ('B = ',B,'+++++\n')
    x = np.zeros(n)
    k = n-1
    x[k] = B[k]/A[k,k]
    while k >= 0:
        x[k] = (B[k] - np.dot(A[k,k+1:], x[k+1:]))/A[k,k]
        k = k-1
    return x

def by_rref(A,B):  # par rref
    Mb = B.col_insert(0,A)
    #print(Mb)
    return Mb.rref()

def by_det(A,B):   # by determinant
    s = []
    det = A.det()
    for k in range(A.shape[1]):    #columns        
        M = Matrix(A)    
        M[:,k] = B
        #print(M)
        s.append(M.det()/det)
    return s

In [53]:
A = np.array([[1.,-1.,1.,-1.],[1.,0.,0.,0.],[1.,1.,1.,1.],[1.,2.,4.,8.]])
#print(Matrix(A))
B =  np.array([[14.],[4.],[2.],[2.]])
m = by_rref(Matrix(A),Matrix(B))
print ('by_rref',m)

by_rref (Matrix([
[1, 0, 0, 0,  4.0],
[0, 1, 0, 0, -5.0],
[0, 0, 1, 0,  4.0],
[0, 0, 0, 1, -1.0]]), (0, 1, 2, 3))


In [50]:
m = by_det(Matrix(A),Matrix(B))
print ('by_determinant',m)

by_determinant [4.00000000000000, -5.00000000000000, 4.00000000000000, -1.00000000000000]


In [31]:
#print(Matrix(B).reshape(4,1))
#print GENP(np.copy(A), np.copy(b))
print (Gauss_pivot(A, B))  

n =  4
[ 4. -5.  4. -1.]


In [47]:
A = Matrix([[1.,-1.,1.,-1.],[1.,0.,0.,0.],[1.,1.,1.,1.],[1.,2.,4.,8.]])
B =  Matrix([[14.],[4.],[2.],[2.]])

det = A.det()
det

12.0000000000000

In [42]:
print(A.shape,len(A))   # len matrice(m,n) = m*n ; len array = m

(4, 4) 16


In [48]:
def by_det(A,B):   # by determinant
    s = []
    det = A.det()
    for k in range(A.shape[1]):    #columns        
        M = Matrix(A)    
        M[:,k] = B
        #print(M)
        s.append(M.det()/det)
    return s

by_det(A,B)

[4.00000000000000, -5.00000000000000, 4.00000000000000, -1.00000000000000]

In [49]:
# argmax
A = np.array([[1.,-1.,1.,-1.],[1.,0.,0.,0.],[1.,1.,1.,1.],[1.,2.,4.,8.]])
print(A, len(A))
for k in range(len(A)):    # rows
    print(A[k:,k])
    maxindex = abs(A[k:,k]).argmax() + k #search max value in column k from row k; +k gives the correct row in array
    print(k,maxindex)

[[ 1. -1.  1. -1.]
 [ 1.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  4.  8.]] 4
[1. 1. 1. 1.]
0 0
[0. 1. 2.]
1 3
[1. 4.]
2 3
[8.]
3 3
